name: Process Dates

on:
  push:
    branches:
      - main  # Cambia esto si es necesario

jobs:
  get_dates:
    runs-on: ubuntu-latest
    outputs:
      dates: ${{ steps.get_dates.outputs.dates }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read dates from JSON
        id: get_dates
        run: |
          dates=$(jq -r '.dates | @csv' dates.json)
          echo "dates=${dates}" >> $GITHUB_ENV

  process_dates:
    runs-on: ubuntu-latest
    needs: get_dates
    strategy:
      matrix:
        date: [${{ env.dates }}]

    steps:
      - name: Process each date
        run: |
          echo "Procesando fecha: ${{ matrix.date }}"
          # Aquí puedes añadir la lógica que necesites para procesar cada fecha
