name: Process Dates and Call NASA API

on:
  push:
    branches:
      - master

jobs:
  cache-api-responses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read JSON file and get dates
        run: |
          echo "Reading dates.json"
          dates=$(jq -r '.dates[]' dates.json)
          echo "::set-output name=dates::$dates"

  call-nasa-api:
    needs: cache-api-responses
    runs-on: ubuntu-latest
    strategy:
      matrix:
        date: ${{ fromJson(needs.cache-api-responses.outputs.dates) }}

    steps:
      - name: Make API request
        id: api_request
        run: |
          url="https://api.nasa.gov/planetary/apod?api_key=${{ secrets.MY_SECRET }}&date=${{ matrix.date }}"
          echo "Making request to: $url"
          response=$(curl -s "$url")
          
          # Crear el directorio para almacenar las respuestas si no existe
          mkdir -p nasa_responses

          # Almacenar la respuesta en un archivo
          echo "$response" > "nasa_responses/response_${{ matrix.date }}.json"
          echo "Response for date ${{ matrix.date }} saved."

  store-in-cache:
    needs: call-nasa-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache API responses
        uses: actions/cache@v3
        with:
          path: ./nasa_responses
          key: nasa-responses-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            nasa-responses-${{ runner.os }}-

      - name: List cached responses
        run: |
          echo "Cached responses:"
          ls nasa_responses