name: Process Dates and Call NASA API

on:
  push:
    branches:
      - main

jobs:
  call-nasa-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read JSON file and process dates
        run: |
          echo "Reading data.json"
          dates=$(jq -r '.dates[]' data.json)

          # Iterar sobre cada fecha y hacer la petición a la API de la NASA
          for date in $dates; do
            url="https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=$date"
            echo "Making request to: $url"
            response=$(curl -s "$url")
            echo "Response for date $date:"
            echo "$response"
          done