name: Process Dates

on:
  push:
    branches:
      - master  # Cambia esto si es necesario

jobs:
  get_dates:
    runs-on: ubuntu-latest
    outputs:
      dates: ${{ steps.get_dates.outputs.dates }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read dates from JSON
        id: get_dates
        run: |
          dates=$(jq -r '.dates[]' dates.json)
          echo "::set-output name=dates::${dates::-1}"  # Eliminar la última coma

  process_dates:
    runs-on: ubuntu-latest
    needs: get_dates
    strategy:
      matrix:
        date: ${{ fromJson(needs.get_dates.outputs.dates) }}
    
    steps:
      - name: Process each date
        run: |
          echo "Procesando fecha: ${{ matrix.date }}"
          # Aquí puedes añadir la lógica que necesites para procesar cada fecha
