name: Process Dates and Call NASA API

on:
  push:
    branches:
      - master

jobs:
  cache-api-responses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read JSON file and get dates
        id: get_dates
        run: |
          echo "Reading dates.json"
          dates=$(jq -r '.dates[]' dates.json)
          echo "::set-output name=dates::$dates"

  call-nasa-api:
    needs: cache-api-responses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read dates from output
        id: read_dates
        run: |
          echo "dates=(${{ needs.cache-api-responses.outputs.dates }})" >> $GITHUB_ENV

      - name: Call NASA API for each date
        run: |
          for date in ${dates[@]}; do
            # Check if response is cached
            if [ -f "nasa_responses/response_$date.json" ]; then
              echo "Response for date $date is already cached. Skipping API call."
              continue
            fi

            # Make API request
            api_url="https://api.nasa.gov/planetary/apod?api_key=${{ secrets.MY_SECRET }}&date=$date"
            echo "Making request to: $api_url"
            
            response=$(curl -s -w "%{http_code}" -o response.json "$api_url")
            
            if [ "$response" -eq 200 ]; then
              echo "Response for date $date saved."
              mv response.json "nasa_responses/response_$date.json"
              
              # Download image
              image_url=$(jq -r '.url' "nasa_responses/response_$date.json")
              echo "Downloading image from: $image_url"
              curl -s -o "img-$date.jpg" "$image_url"
              echo "Image downloaded as img-$date.jpg"
              
              # Upload image as artifact
              echo "Uploading img-$date.jpg as artifact."
              echo "::set-output name=image_artifact::img-$date.jpg"
              echo "Uploading artifact: img-$date.jpg"
              gh api -X POST "/repos/${{ github.repository }}/actions/artifacts" -F name="img-$date" -F path="img-$date.jpg"
            else
              echo "Error: Received response code $response for date $date. Skipping."
              rm response.json
            fi
          done

  store-in-cache:
    needs: call-nasa-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache API responses
        uses: actions/cache@v3
        with:
          path: ./nasa_responses
          key: nasa-responses-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            nasa-responses-${{ runner.os }}-

      - name: List cached responses
        run: |
          echo "Cached responses:"
          ls nasa_responses
